name: ğŸ•µï¸ PR Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  actions: write
  contents: read

jobs:
  pr_checks:
    name: ğŸš¦ PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ’¾ Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: v18.18.0

      - uses: pnpm/action-setup@v2
        name: ğŸ•œ Install pnpm
        with:
          run_install: false

      - name: ğŸ• Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: ğŸ• Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: ğŸªª Check licenses
        run: pnpm check:licenses

      - name: ğŸ§ Prettier
        run: pnpm prettier:check

      - name: ğŸ«£ Lint
        run: pnpm lint

      - name: ğŸ§ª Unit test
        run: pnpm test:unit --run

      - name: ğŸ—ï¸ Build
        run: pnpm build
